### ISSUE TITLE
Bitmap print on other thermal printers

### ISSUE THREAD

**Issue by AndersV209** [adafruit/Adafruit-Thermal-Printer-Library#18]
Hello 

i have a samsung srp-350 POS thermal printer and i cant get the bitmap image function to work, it just prints random charaters instead of the image 

![2015-08-22 23 05 00](https://cloud.githubusercontent.com/assets/11842000/9425865/58ee07e6-4922-11e5-9862-e72698842758.jpg)

**Comment by AndersV209** [comment]
i found a fix for the problem, and i also made some new functions like cut the paper and make the printer beep, so i made a new library https://github.com/AndersV209/Pos-Printer-Library

**Comment by rezanahardani** [comment]
change the begin(---);
9600 or 19200

**Comment by benolayinka** [comment]
@AndersV209 but what was the fix?

**Comment by caternuson** [comment]
Closing. Looks like solution is to use fork linked above.
