### ISSUE TITLE
printBitmap function restricted to 255px width

### ISSUE THREAD

**Issue by kabrio** [adafruit/Adafruit-Thermal-Printer-Library#2]
the function to print images needs a fix.

does not allow images larger than 255px in width to be printed.

it is possible though, as other projects, using the same printer, show.
by example: http://electronicfields.wordpress.com/2011/10/09/sharing-links-physically/
code of this project available at github.
look for PrintImage function here: https://github.com/yukimizake/ThermalDotNet/blob/master/ThermalDotNet/ThermalPrinter.cs

should be easy to implement in adafruits Thermal Printer Lib, will have a look when i find time, but would appreciate pros to look at it!

cheers,
k

**Comment by thearduinoguy** [comment]
Has this been fixed in THIS library?
