### ISSUE TITLE
All examples are still using SoftwareSerial Library

### ISSUE THREAD

**Issue by jmzuazo** [adafruit/Adafruit-Thermal-Printer-Library#21]
Arduino: 1.6.7 (Mac OS X), Board: "Intel® Edison"

/Users/.../Documents/Arduino/libraries/Adafruit_Thermal_Printer/examples/A_printertest/A_printertest.ino:21:28: fatal error: SoftwareSerial.h: No such file or directory
 #include "SoftwareSerial.h"
                            ^
compilation terminated.
exit status 1
Error compiling.

**Comment by caternuson** [comment]
Closing. Examples now have commented out code showing how to use hardware serial. Default is still software though.
