### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by vwasteels** [adafruit/Adafruit-Thermal-Printer-Library#27]
Hello,

I'm wondering if there is any NodeJs alternative to this library ?

Thank you,
Vincent

**Comment by caternuson** [comment]
Not that we know of, but there may be one. Just need to have NodeJS code that does equivalent serial comms.

**Comment by stuffshit** [comment]
> Hello,
> 
> I'm wondering if there is any NodeJs alternative to this library ?
> 
> Thank you, Vincent

Hey, I did one a few years ago, but it doesn't support image printing https://github.com/stuffshit/thermal
