### ISSUE TITLE
Firmware for printer

### ISSUE THREAD

**Issue by Lepeshka92** [adafruit/Adafruit-Thermal-Printer-Library#28]
Where can I find the latest firmware for thermal printer? QR204

**Comment by kaiaseamus** [comment]
Printer firmware is the actual program that is installed in a printer when it is first manufactured. The firmware tells the printer everything it needs to know to operate correctly and to interact with a PC
https://bit.ly/2H0JNI9

**Comment by ChrisIdema** [comment]
I'm curious about whether or not firmware can be updated. I have printer #597 with unknown firmware version

**Comment by caternuson** [comment]
There's an **unsupported** option here:
https://learn.adafruit.com/mini-thermal-receipt-printer/downloads#firmware-changer-1825755-2
