### ISSUE TITLE
Can't change codepage on firmware 2.69

### ISSUE THREAD

**Issue by zhovner** [adafruit/Adafruit-Thermal-Printer-Library#29]
I'm try to use another codepage by `setCodePage()`.
No matter what codepage I setup, I still get chinese symbols in upper ASCII.
But changing charset by `setCharset()` working correctly.

Here the test page I get when press button during power on: 
![image](https://user-images.githubusercontent.com/774290/39559297-c22e73a2-4e9d-11e8-886d-d2aa5462c725.png)

**Comment by masteruan** [comment]
Me too

**Comment by 0julio0** [comment]
Same problem. Any sugestion?

**Comment by zhovner** [comment]
@0julio0 I give up trying to fix this and use bitmap image to print custom symbols

**Comment by shali379** [comment]
For some reason the Kanji mode is switched on by default. Before changing codepage, the Kanji mode must be disabled by sending the "Cancel Kanji character mode" command. The setCodePage function thus should read:
`void Adafruit_Thermal::setCodePage(uint8_t val) {`
`  if(val > 47) val = 47;`
`  writeBytes(ASCII_FS, '.'); //Cancel Kanji character mode`
`  writeBytes(ASCII_ESC, 't', val);`
`}`
I was able to set the CP1250 (West Europe) successfully this way.
Note that my printer is "VERSION 2.69 2013-11-22" and I have no idea how other printer versions will react to this command.

**Comment by masteruan** [comment]
Doesn't work for me :-(

**Comment by masteruan** [comment]
I've resolved my problem!! I've removed the RS232 --> TTL converter. And added some resistance under the component like in photo.
![components_pcbscrews](https://user-images.githubusercontent.com/6987018/52624872-0684d080-2eb0-11e9-9efb-64a5586b67fa.jpg)

**Comment by lomalkin** [comment]
> I've resolved my problem!! I've removed the RS232 --> TTL converter. And added some resistance under the component like in photo.
> ![components_pcbscrews](https://user-images.githubusercontent.com/6987018/52624872-0684d080-2eb0-11e9-9efb-64a5586b67fa.jpg)

Confirmed. Thank you!
I also fixed two chinese printers by removing UT3232 and adding four resistors 470R 0603.

**Comment by caternuson** [comment]
Is this happening with any of the printers sold by Adafruit? This may be a region specific hardware issue?

**Comment by caternuson** [comment]
Closing. Can not recreated with a [PID 2751 printer](https://www.adafruit.com/product/2751), a [Feather ESP32](https://www.adafruit.com/product/3405), and using the `B_charsets.ino` example from library.

Please provide information on the specific printer model being used.


![esp32_test](https://user-images.githubusercontent.com/8755041/114236152-0d93b600-9936-11eb-824f-614ccd914ecf.jpg)
