### ISSUE TITLE
Bitmap centralize

### ISSUE THREAD

**Issue by Thibis** [adafruit/Adafruit-Thermal-Printer-Library#35]
Hi everyone!

Is it possible to centralize a bitmap?

Regards

**Comment by sverdejot** [comment]
You have to edit your bitmap using Photoshop or some app like that.

Just add padding at left.

If using photoshop, do the following:

1. Create a new file with size in pixels:
 - width: ((384 - your bitmap width)/2) + your bitmap width 
 - height: your bitmap height
2. place your bitmap to right margin of the new file. 
3. Export it as png and save as bmp monochrome using paint. 

Then you can save as .h using LCDAssistant

**Comment by caternuson** [comment]
Yep, that, or something similar, is how you'll have to do it for now.
