### ISSUE TITLE
Carriage return 0x13 ?

### ISSUE THREAD

**Issue by HamzaHajeir** [adafruit/Adafruit-Thermal-Printer-Library#40]
Hi

While I'm enhancing the performance of this library by making it non-blocking, I've noticed this line : 

`if(c != 0x13) { // Strip carriage returns `

Shouldn't It be 13 Decimal, Not HEX ? 
`if(c != 13) { // Strip carriage returns`

Or someone waits Ariana 6 to happen here ? xD

Thanks

**Comment by ladyada** [comment]
right! could you submit a PR? :)

**Comment by HamzaHajeir** [comment]
At soonest :) 

I'll prepare my enhanced version of this library, Can you open a dev-branch to make PR to it ?

Thanks

**Comment by ladyada** [comment]
you would fork it yourself
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control

**Comment by HamzaHajeir** [comment]
Of-course I'd do it on my fork first, I've merged 2 forks already ;) 

But I want to do 2 separate PRs, One for CR, and one for library enhancement.

**Comment by ladyada** [comment]
ok! please PR into `master`

**Comment by caternuson** [comment]
Fixed with #44.
